title: GRID Lab
description: The GRID Lab
paginate: 10
baseurl: ''


social:
  twitter: https://www.twitter.com/gridlab
  facebook:
  github:
  linkded-in :
  google-plus:
    
collections:
  tech:
    permalink: /tech/:path/
    output: true
  projects:
    permalink: /projects/:path/
    output: true
  team:

defaults:
  - scope:
      type: tech
    values:
      layout: left-sidebar
      
  - scope:
      type: projects
    values:
      layout: left-sidebar