title: GRID Lab
description: The GRID Lab
keywords:
paginate: 10
baseurl: ''
banner: /assets/images/gl-banner-2.jpg

social:
  twitter: https://www.twitter.com/gridlab
  facebook: https://www.facebook.com/gridlab/
  github:
  linkded-in :
  google-plus:

collections:
  tech:
    permalink: /tech/:path/
    output: true
  projects:
    permalink: /projects/:path/
    output: true
  team:

defaults:
  - scope:
      type: pages
    values:
      banner: /assets/images/gl-banner-2-small.jpg

  - scope:
      type: tech
    values:
      layout: left-sidebar
      banner: /assets/images/gl-banner-1-small.jpg

  - scope:
      type: projects
    values:
      layout: left-sidebar
      banner: /assets/images/gl-banner-2-small.jpg

  - scope:
      type: posts
    values:
      banner: /assets/images/default-hacker.jpg
      layout: post
